services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: 
           - "@mailer"
           - "%locale%"
           - 50
    oc_platform.load_category:
        class: OC\PlatformBundle\DataFixtures\LoadCategory
        tags: [doctrine.fixture.orm]
        
    oc_platform.load_skill:
        class: OC\PlatformBundle\DataFixtures\LoadSkill
        tags: [doctrine.fixture.orm]
            